### PR TITLE
Redirects/scholarship impact sthfund

### PR DESCRIPTION
**Pull request by Adam42**

### CODE REVIEW

**Comment by Adam42** [comment]
@anton-kachurin @jdub233 could you take a look and if it looks good ask @bfenster to merge in?

**Review by anton-kachurin — APPROVED** [review]

**Comment by Adam42** [comment]
Both clients are asking for updates and Ben is out so merging this in. @jdub233 @anton-kachurin @ronyeany could one of you confirm in ~20 minutes these redirects are active and update tickets?

**Comment by anton-kachurin** [comment]
http://www.bu.edu/scholarshipimpact
http://www.bu.edu/sthfund

~both return 404~

4pm update: work normally

**Comment by anton-kachurin** [comment]
Updated the clients (Adam's messages were marked as work notes so sent client-visible messages)

**Pull request merged**
